server:
  port: 8888

spring:
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@oracle.coffit.site:1521:xe
    username: C##NULLCROWD
    password: NULLCROWD
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
      location: C:\DEV\04_project\NullCrowd
  devtools:
    restart:
      enabled: false
    livereload:
      enabled: true
  freemarker:
    cache: false
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false
    check-template-location: true
  web:
    resources:
      static-locations: classpath:/upload/
  image:
    image-dir:src/main/resources/static
  mail:
    host: smtp.gmail.com
    port: 587
    username: bs11mailsender@gmail.com
    password: ssvhtxnbjlhajjpp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true


#mybatis mapping
mybatis:
  type-aliases-package: com.teamtwo.nullfunding
  mapper-locations: /mybatis/mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true

  logging:
    level:
      root: info
